<errormap>

<!-- category = FTS, SRM, gridftp, phedex, unknown -->
<!-- origin = source, dest, client, unknown, -->

<!-- see also https://twiki.cern.ch/twiki/bin/view/LCG/TransferOperationsPopularErrors -->
<!-- https://twiki.cern.ch/twiki/bin/view/LCG/TransferOperationsGridFTPErrors -->

<!-- http://www.tareeinternet.com/forum/knowledgebase/51-ftp-error-codes-messages.html -->
<!-- http://www.the-eggman.com/seminars/ftp_error_codes.html -->
<!-- http://www.cisco.com/en/US/docs/ios/sw_upgrades/interlink/r2_0/unpremsg/muftp.html -->

<error cat="SRM" origin="dest">
<pattern> DESTINATION error during PREPARATION phase: [USER] failed to contact on remote SRM
</pattern>
<desc>
Unavailability of SRM
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [CONNECTION] failed to contact on remote SRM
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern> DESTINATION error during PREPARATION phase: [REQUEST_TIMEOUT] failed to prepare Destination file in
</pattern>
<desc>
in 180,200,etc seconds. Unavailability of SRM
</desc>
</error>

<error cat="SRM" origin="source">
<pattern> SOURCE error during PREPARATION phase: [REQUEST_TIMEOUT] failed to prepare source file in
</pattern>
<desc> in 180,200,etc seconds. Unavailability of SRM, file can not be staged in etc
</desc>
</error>


<error cat="SRM" origin="dest">
<pattern> DESTINATION error during FINALIZATION phase: [GENERAL_FAILURE] failed to complete PrepareToPut request
</pattern>
<desc>
</desc>
</error>

<error cat="unknown" origin="unknown">
<pattern> TRANSFER error during TRANSFER phase: [GRIDFTP] the name
</pattern>
<desc>continuation: _destination host_ could not be resolved
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [PERMISSION] [SrmPing] failed: SOAP-ENV:Client - CGSI-gSOAP: Error initializing context
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [PERMISSION] [SrmPing] failed: SOAP-ENV:Client - CGSI-gSOAP: Error initializing context
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [PERMISSION] [srm2__srmStatusOfGetRequest] failed: SOAP-ENV:Client - CGSI-gSOAP: Error initializing context
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [PERMISSION] [srm2__srmPrepareToGet] failed: SOAP-ENV:Client - CGSI-gSOAP: Error initializing context
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [GENERAL_FAILURE] Error creating statement, Oracle code:
</pattern>
<desc> +12560
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [GENERAL_FAILURE] stage_prepareToPut: Internal Error
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [GENERAL_FAILURE] stage_put error: Unknown internal error
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [GENERAL_FAILURE] Error in insert request
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] RQueued
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] Castor Error caught in srm::getUserFile:
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] All copies of this file are unavailable for now. Please retry later
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] Unknown error 1015
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] Error in fillRep for type 1008
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] Error while committing
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [CONNECTION] [SrmPut] failed: SOAP-ENV:Client - CGSI-gSOAP: Could not open connection
</pattern>
<desc>
</desc>
</error>


<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [CONNECTION] [srm2__srmPrepareToPut] failed: SOAP-ENV:Client - CGSI-gSOAP: Could not open connection
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [CONNECTION] [srm2__srmPrepareToGet] failed: SOAP-ENV:Server - CGSI-gSOAP: Could not find mapping for:
</pattern>
<desc> +DN
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [CONNECTION] [srm2__srmPrepareToGet] failed: SOAP-ENV:Client - CGSI-gSOAP: Could not open connection
</pattern>
<desc>
</desc>
</error>


<error cat="gridftp" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (Unexpected Exception : org.dcache.ftp.FTPException: Received block with unknown descriptor (105)/Broken pipe)
</pattern>
<desc>
</desc>
</error>

<error cat="gridftp" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (Unexpected Exception : java.nio.channels.UnresolvedAddressException)
</pattern>
<desc>
</desc>
</error>

<error cat="gridftp" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (java.lang.OutOfMemoryError)
</pattern>
<desc>
</desc>
</error>

<error cat="gridftp" origin="source">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (Unexpected Exception : java.io.IOException: Connection timed out)
</pattern>
<desc>so dcache client tries to connect but failes. who's side is this? Seems to be source.
</desc>
</error>

<error cat="gridftp" origin="source">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (Unexpected Exception : java.net.ConnectException: Connection timed out)
</pattern>
<desc>so dcache client tries to connect but failes. who's side is this? Seems to be source.
</desc>
</error>

<error cat="gridftp" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (Incomplete file detected)
</pattern>
<desc>
</desc>
</error>

<error cat="gridftp" origin="source">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (PANIC : Unexpected message arrived class dmg.cells.nucleus.NoRouteToCellException)
</pattern>
<desc>Erro when Castor/DPM at source. Seems to be source at fault
</desc>
</error>


<error cat="gridftp" origin="source">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Data connection. data_write() failed: Handle not in the proper state
</pattern>
<desc>Erro when Castor/DPM at source. Reasons - - means that the side sending out data encountered an error while sending the data to the ftp subsystem. However often this simply indictaes that the TCP data connection(s) closed - probably the peer closed them although network problems have also been known to cause the connection to reset. Maarten Litmaath comment - "The network problems could be caused by firewalls that
either are too strict (sometimes hardcoded in the firmware) or otherwise misconfigured
</desc>
</error>


<error cat="gridftp" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (Unexpected Exception : java.lang.InterruptedException)
</pattern>
<desc>Is this the same error that show up when dcache transfers from Castor/DPM and they close connection by timeout?
</desc>
</error>


<error cat="gridftp" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (Unexpected Exception : java.io.IOException: Broken pipe)
</pattern>
<desc>
</desc>
</error>

<error cat="gridftp" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (Unexpected Exception : java.lang.InterruptedException/Broken pipe)
</pattern>
<desc>
</desc>
</error>


<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] FAILED: at [date] state Running : executing
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] FAILED: at [date] state TQueued : put on the thread queue
</pattern>
<desc>
</desc>
</error>


<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] FAILED: at [date] state Failed : No Route to cell for packet
</pattern>
<desc>
</desc>
</error>


<error cat="gridftp" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (Unexpected Exception : java.net.ConnectException: Connection refused)
</pattern>
<desc>I guess the source is refusing connection to dCache
</desc>
</error>

<error cat="phedex" origin="client">
<pattern>(null)
</pattern>
<desc>This means error needs better parsing in InspectPheddexLog
</desc>
</error>

<error cat="phedex" origin="client">
<pattern>Could not submit to FTS
</pattern>
<desc>
</desc>
</error>

<error cat="phedex" origin="client">
<pattern> agent lost the transfer
</pattern>
<desc>
</desc>
</error>


<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [GENERAL_FAILURE] Error caught in srm::getSrmUser.
</pattern>
<desc>Seems to be Castor problem, as only appears for castor end
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] Error caught in srm::getSrmUser.
</pattern>
<desc>Seems to be Castor problem, as only appear for castor end
</desc>
</error>



<error cat="gridftp" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [TRANSFER_TIMEOUT] gridftp_copy_wait: Connection timed out
</pattern>
<desc>Reasons - transfer takes too long or some (control or data) connection could not even be made
</desc>
</error>


<error cat="SRM" origin="dest">
<pattern>DESTINATION error during TRANSFER phase: [TRANSFER_TIMEOUT] globus_ftp_client_size: Connection timed out
</pattern>
<desc>Seems to be a Castor problems, as only appears for Castor end. Reasons - getting information takes too long or the connection could not be established
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during TRANSFER phase: [TRANSFER_TIMEOUT] globus_ftp_client_size: Connection timed out
</pattern>
<desc>Seems to be a Castor problems, as only appears for Castor end. Reasons - getting information takes too long or the connection could not be established
</desc>
</error>


<error cat="SRM" origin="source">
<pattern>DESTINATION error during PREPARATION phase: [CONNECTION] service timeout during [srm2__srmPrepareToPut]
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [CONNECTION] service timeout during [srm2__srmPrepareToGet] 
</pattern>
<desc>
</desc>
</error>


<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] Error in getting type from id.
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [GENERAL_FAILURE] stage_put error: Job timed out while waiting to be scheduled
</pattern>
<desc>Castor problem serving a file
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 500 500 Command failed. : open error: Job timed out while waiting to be scheduled
</pattern>
<desc>Castor problem serving a file
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>TRANSFER error during TRANSFER phase: [PERMISSION] the server sent an error response: 500 500 Command failed. : open error: Permission denied
</pattern>
<desc>Castor problem serving a file
</desc>
</error>


<error cat="gridftp" origin="source">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 500 500-Command failed. : an I/O operation was cancelled
</pattern>
<desc>
</desc>
</error>

<error cat="gridftp" origin="source">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 500 500-Command failed. : connection prematurly closed
</pattern>
<desc>
</desc>
</error>

<error cat="gridftp" origin="source">
<pattern>SOURCE error during TRANSFER phase: [GRIDFTP] the server sent an error response: 500 500 java.lang.reflect.InvocationTargetException:
</pattern>
<desc>
</desc>
</error>

<error cat="gridftp" origin="source">
<pattern>SOURCE error during TRANSFER phase: [PERMISSION] the server sent an error response: 500 500 Error: GSSException: No valid credentials provided
</pattern>
<desc>
</desc>
</error>

<error cat="gridftp" origin="source">
<pattern>TRANSFER error during TRANSFER phase: [PERMISSION] the server sent an error response: 500 500 Error: GSSException: No valid credentials provided
</pattern>
<desc>
</desc>
</error>

<error cat="gridftp" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 500 500-Command failed. : globus_xio:
</pattern>
<desc>
</desc>
</error>


<error cat="gridftp" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 500 500 Command failed. : open error: Timed out 
</pattern>
<desc>
</desc>
</error>


<error cat="gridftp" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 451 451 Aborting transfer due to session termination
</pattern>
<desc>rare error
</desc>
</error>

<error cat="gridftp" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 451 451 Internal timeout
</pattern>
<desc>rare error
</desc>
</error>

<error cat="gridftp" origin="dest">
<pattern> TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 451 451 Local resource failure: malloc: Cannot allocate memory.
</pattern>
<desc>This is a Castor/DPM problem when they are source? After a timeout caused by inactivity on the data channels the CASTOR Grid-ftp server (at VDT level) tries to read the rest of the file into memory and fails on the malloc because the memory limit on such processes has been set low (50 MB), exactly to cause the process to fail and exit under such circumstances: the destination had a problem with writing the data, then it stalled.
</desc>
</error>

<error cat="gridftp" origin="dest">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 451 451 Operation failed: FTP Door: got response from '[PoolManager stuff]' with error [No write pools configured for
</pattern>
<desc>dCache config error
</desc>
</error>

<error cat="gridftp" origin="dest">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 451 451 Operation failed: FTP Door: got response from '[PoolManager stuff]' with error No write pool available for
</pattern>
<desc>dCache config error
</desc>
</error>

<error cat="gridftp" origin="dest">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 451 451 Operation failed: Non-null return code from '[PoolManager stuff]' with error No write pool available for 
</pattern>
<desc>dCache config error
</desc>
</error>

<error cat="gridftp" origin="dest">
<pattern>
TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 451 451 Operation failed: FTP Door: got response from '[SrmSpaceManager stuff]' with error java.sql.SQLException: Already have 1 record(s) with pnfsPath=path
</pattern>
<desc>dCache erro - apparently when there is two transfers going on for the same destintions file. While it should be more or less fixed at the servers side to give a better error, it is really a client error, since he should not start two transfers for the same destination file.
</desc>
</error>


<error cat="gridftp" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] an end-of-file was reached (possibly the destination disk is full)
</pattern>
<desc>No, this is not destination disk at fault usually. Error transmitted by the dCache client when file system is full or the data connection was closed prematurely for any other reason
</desc>
</error>

<error cat="gridftp" origin="unknown">
<pattern>SOURCE error during TRANSFER phase: [GRIDFTP] an end-of-file was reached (possibly the destination disk is full)
</pattern>
<desc>No, this is not destination disk at fault, usually. Error transmitted by the dCache client when file system is full or the data connection was closed prematurely for any other reason.
</desc>
</error>


<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [CONNECTION] [srm2__srmPrepareToGet] failed: SOAP-ENV:Client - CGSI-gSOAP: Error reading token data header:
</pattern>
<desc>+ Connection closed, Connection reset by peer
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [CONNECTION] [srm2__srmPrepareToPut] failed: SOAP-ENV:Client - CGSI-gSOAP: Error reading token data header:
</pattern>
<desc>+ Connection closed, Connection reset by peer. Seems to be Castor
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [CONNECTION] [srm2__srmPrepareToGet] failed: SOAP-ENV:Client - CGSI-gSOAP: Error sending token data: Connection reset by peer
</pattern>
<desc>
</desc>
</error>

<error cat="gridftp" origin="source">
<pattern>SOURCE error during TRANSFER phase: [GRIDFTP] globus_ftp_control_connect: globus_libc_gethostbyaddr_r failed
</pattern>
<desc>
</desc>
</error>


<error cat="gridftp" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] globus_ftp_control_connect: globus_libc_gethostbyaddr_r failed
</pattern>
<desc>
</desc>
</error>


<error cat="" origin="">
<pattern> 
</pattern>
<desc>rare error
</desc>
</error>


<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [GENERAL_FAILURE] at [date] state Failed : Marking Space as Being Used failed =>Already have 1 record(s) with pnfsPath=
</pattern>
<desc>dcache error
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [GENERAL_FAILURE] RequestFileStatus#[number] failed with error:[ at [date] state Failed : Marking Space as Being Used failed  
</pattern>
<desc>
</desc>
</error>


<error cat="SRM" origin="dest">
<pattern>DESTINATION error during TRANSFER phase: [INVALID_SIZE]
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>DESTINATION error during TRANSFER phase: [INVALID_SIZE] empty file size returned
</pattern>
<desc>Reasons - the file exists, but has a zero file size. Such files can be left by ungracefully terminated requests
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [INVALID_PATH] Failed
</pattern>
<desc>file is missing at the source
</desc>
</error>


<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [FILE_EXISTS]
</pattern>
<desc>File exists at source
</desc>
</error>


<error cat="gridftp" origin="source">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (Unexpected Exception : java.io.IOException: Connection reset by peer)
</pattern>
<desc>dcache client is connected, but the other end closes the connection.
</desc>
</error>

<error cat="gridftp" origin="source">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (Unexpected Exception : java.io.IOException: Interrupted system call)
</pattern>
<desc>dcache client is connected, but the other end closes the connection.
</desc>
</error>

<error cat="gridftp" origin="source">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (Unexpected Exception : java.io.IOException: Interrupted system call/adapter did not shut down)
</pattern>
<desc>dcache client is connected, but the other end closes the connection.
</desc>
</error>

<error cat="gridftp" origin="source">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (Unexpected Exception : java.lang.InterruptedException/adapter did not shut down)
</pattern>
<desc>dcache client is connected, but the other end closes the connection.
</desc>
</error>


<error cat="gridftp" origin="source">
<pattern>SOURCE error during TRANSFER phase: [GRIDFTP] globus_l_ftp_control_send_cmd_cb: gss_init_sec_context failed
</pattern>
<desc>
</desc>
</error>


<error cat="SRM" origin="source">
<pattern>DESTINATION error during PREPARATION phase: [GENERAL_FAILURE] rfio_open error: Timed out
</pattern>
<desc>Castor problem
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>DESTINATION error during PREPARATION phase: [GENERAL_FAILURE] rfio_open error: Permission denied
</pattern>
<desc>Castor problem, but is it really "source"? to be checked
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [USER] [srm-URL] : Permission denied
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [USER] Permission denied
</pattern>
<desc>
</desc>
</error>


<error cat="gridftp" origin="source">
<pattern>SOURCE error during TRANSFER phase: [GRIDFTP] the server sent an error response: 550 550 Command failed : rfio_stat64 error:
</pattern>
<desc>Castor problem
</desc>
</error>

<error cat="gridftp" origin="source">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 550 550 Command failed : rfio_stat64 error:
</pattern>
<desc>Castor problem
</desc>
</error>

<error cat="gridftp" origin="dest">
<pattern>DESTINATION error during TRANSFER phase: [INVALID_PATH] the server sent an error response: 550 550 Command failed : rfio_stat64 error:
</pattern>
<desc>+No such file or directory .Castor problem 
</desc>
</error>



<error cat="gridftp" origin="source">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 550 550 [path] not a plain file
</pattern>
<desc>Need to see actual logs to get the file name
</desc>
</error>

<error cat="gridftp" origin="source">
<pattern>SOURCE error during TRANSFER phase: [GRIDFTP] the server sent an error response: 550 550 [path] not a plain file
</pattern>
<desc>Need to see actual logs to get the file name
</desc>
</error>

<error cat="gridftp" origin="dest">
<pattern>DESTINATION error during TRANSFER phase: [GRIDFTP] the server sent an error response: 550 550 Command failed : rfio_stat64 error:
</pattern>
<desc>Castor problem
</desc>
</error>


<error cat="gridftp" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] a system call failed
</pattern>
<desc>rare castor error + (Connection timeout), (Connection rest by peer)
</desc>
</error>

<error cat="gridftp" origin="source">
<pattern>SOURCE error during TRANSFER phase: [GRIDFTP] a system call failed (Connection refused)
</pattern>
<desc>rare castor error
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [INTERNAL_ERROR] SRM returned an error, but with an invalid code [SRM_SUCCESS]
</pattern>
<desc>rare error
</desc>
</error>

<error cat="gridftp" origin="source">
<pattern> TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (Unexpected Exception : org.dcache.ftp.FTPException: Stream ended before EOD/Data channel was closed before EOD marker)
</pattern>
<desc>
</desc>
</error>

<error cat="gridftp" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (Unexpected Exception : org.dcache.ftp.FTPException: Stream was closed in the middle of a block/Data channel was closed before EOD marker)
</pattern>
<desc>rare error
</desc>
</error>


<error cat="SRM" origin="dest">
<pattern>TRANSFER error during TRANSFER phase: [PERMISSION] the server sent an error response: 553 553 Permission denied, reason: CacheException(rc=10006;msg=Pnfs request timed out)
</pattern>
<desc>rare error, seems to be dcache internal affairs
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>TRANSFER error during TRANSFER phase: [PERMISSION] the server sent an error response: 553 553 Permission denied, reason: CacheException(rc=10000;msg=PANIC : Unexpected message arrived class dmg.cells.nucleus.NoRouteToCellException)
</pattern>
<desc>rare error, seems to be dcache internal affairs
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during TRANSFER phase: [PERMISSION] the server sent an error response: 553 553 Permission denied, reason: CacheException(rc=10001;msg=path [path]
</pattern>
<desc>rare error
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during TRANSFER phase: [PERMISSION] globus_l_ftp_control_send_cmd_cb: gss_init_sec_context failed
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>the server sent an error response: 553 553 [filename]:  Cannot create file: Pnfs request timed out
</pattern>
<desc>rare error
</desc>
</error>


<error cat="gridftp" origin="unknown">
<pattern> TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 500 500 java.lang.reflect.InvocationTargetException:
</pattern>
<desc>
</desc>
</error>


<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [INVALID_PATH] Requested file is still in SRM_SPACE_AVAILABLE state!
</pattern>
<desc>
</desc>
</error>



<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] Castor status for this file is INVALID_STATUS 
</pattern>
<desc>
</desc>
</error>


<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [INVALID_PATH] No such file or directory 
</pattern>
<desc>
</desc>
</error>


<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [CONNECTION] failed to contact on remote SRM
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="client">
<pattern>DESTINATION error during PREPARATION phase: [USER] [srm-URL] : parent path or a component of the parent path does not exist
</pattern>
<desc>
</desc>
</error>



<error cat="SRM" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 500 500 Command failed. : open/create error
</pattern>
<desc>Error transferring to Castor
</desc>
</error>

<error cat="SRM" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 500 500 Command failed. : open error: Invalid argument
</pattern>
<desc>Error transferring to Castor
</desc>
</error>


<error cat="SRM" origin="unknown">
<pattern>TRANSFER error during TRANSFER phase: [TRANSFER_TIMEOUT] globus_gass_copy_register_url_to_url: Connection timed out
</pattern>
<desc>Error transferring to Castor. Reasons - high load on channel, copying takes too long or some connection could not even be made, e.g. due to high load on the channel or on the network, or due to network/firewall problems.
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] FAILED: at [date] state AsyncWait :
</pattern>
<desc>Castor. + getting file Id, pinning file
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] AsyncWait
</pattern>
<desc>Castor
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] source file failed on the SRM with error [SRM_FAILURE]
</pattern>
<desc>
</desc>
</error>


<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] cannot continue since no size has been returned after PrepareToGet or SrmStat
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [PERMISSION] Failed to (re)create the file
</pattern>
<desc>Castor
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] Invalid Status returned by the SRM [SRM_INTERNAL_ERROR]. Consider it as generic failure. Original error message was: File in invalid status
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] No tape segment found
</pattern>
<desc>Castor
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [USER] Unknown error while stating file
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="source">
<pattern>SOURCE error during PREPARATION phase: [GENERAL_FAILURE] StoRM encountered an unexpected error!
</pattern>
<desc>
</desc>
</error>


<error cat="SRM" origin="source">
<pattern>SOURCE error during TRANSFER phase: [GRIDFTP] the server sent an error response: 530 530 Authorization Service failed:
</pattern>
<desc>diskCacheV111.services.authorization.AuthorizationServiceException:authRequestID [id] Message to gPlazma timed out for authentification of +DN
dCache error
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 530 530 Authorization Service failed:
</pattern>
<desc>diskCacheV111.services.authorization.AuthorizationServiceException:authRequestID [id] Message to gPlazma timed out for authentification of +DN
dCache error
</desc>
</error>

<error cat="phedex" origin="client">
<pattern>no detail - validate failed:
</pattern>
<desc>
</desc>
</error>

<error cat="gridftp" origin="dest">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (Exception sending pnfs request : java.lang.InterruptedException)
</pattern>
<desc>seems to be dcache internal affairs
</desc>
</error>

<error cat="gridftp" origin="source">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 426 426 Transfer aborted (Unexpected Exception : java.lang.IllegalArgumentException: invalid prm_offset=0 and prm_size [size] for file of size 0)
</pattern>
<desc>
</desc>
</error>

<error cat="SRM" origin="dest">
<pattern>DESTINATION error during PREPARATION phase: [USER] Too many threads busy with Castor at the moment
</pattern>
<desc>
</desc>
</error>

<error cat="gridftp" origin="unknown">
<pattern>the server sent an error response: 425 425 Can't open data connection
</pattern>
<desc>
</desc>
</error>

<error cat="gridftp" origin="dest">
<pattern>the server sent an error response: 425 425 Can't open data connection. timed out() failed
</pattern>
<desc>Maarten Litmaath comment - "This can have at least 2 causes:1. The connection to the data port (in the destination GLOBUS_TCP_PORT_RANGE) is blocked by a firewall or by a temporary network problem. 2. The connection succeeded, but the data transfer timed out. Also this problem is due to the destination.
</desc>
</error>


<error cat="gridftp" origin="dest">
<pattern>The server sent an error response: 421 421 Timeout (900 seconds): closing control connection.
</pattern>
<desc>Reasons - bug in the gridftp code in retrieve() in ftpd.c. Maarten Litmaath comment - "That bug is triggered by another problem: the operation timed out. As far as I remember, the error is always due to the destination"
</desc>
</error>

<error cat="gridftp" origin="dest">
<pattern>TRANSFER error during TRANSFER phase: [GRIDFTP] the server sent an error response: 421 421 Timeout (900 seconds): closing control connection.
</pattern>
<desc>Reasons - bug in the gridftp code in retrieve() in ftpd.c. Maarten Litmaath comment - "That bug is triggered by another problem: the operation timed out. As far as I remember, the error is always due to the destination"
</desc>
</error>

<error cat="FTS" origin="FTS">
<pattern>Failed to get proxy certificate from myproxy-fts.cern.ch . Reason is Error in bind()
</pattern>
<desc>
</desc>
</error>



</errormap>



<!-- error template

<error cat="" origin="">
<pattern>
</pattern>
<desc>
</desc>
</error>


-->
